language: python

python:
    - "3.7"

before_install:
    - sudo apt-get install python3-tk

script:
    - echo "*****       Build Starting       *****"
    - pip install -e .
    - pip install -r requirements.txt
    - echo "*****      Build Sucessfull      *****"
    - echo "*****      Testing Starting      *****"
    - pytest tests
    - echo "*****     Testing Sucessfull     *****"
