sudo: false

language: python

python:
    - "3.7"

before_install:
    - sudo apt-get install python3-tk

script:
    - echo "*****       Build Starting       *****"
    - pip install -e .
    - pip install -r requirements.txt
    - pip install pytest pytest-cov
    - echo "*****      Build Sucessfull      *****"
    - echo "*****      Testing Starting      *****"
    - pytest tests
    - pytest --cov=./src
    - bash <(curl -s https://codecov.io/bash)
    - echo $CODECOV_TOKEN
    - echo "token"
    - env
    - printenv
    - echo "*****     Testing Sucessfull     *****"
    
after_success:
    - codecov -t CODECOV_TOKEN