sudo: false

language: python

python:
    - "3.7"

before_install:
    - sudo apt-get install python3-tk

install:
    - pip install pytest pytest-cov

script:
    - echo "*****       Build Starting       *****"
    - pip install -e .
    - pip install -r requirements.txt
    - echo "*****      Build Sucessfull      *****"
    - echo "*****      Testing Starting      *****"
    - pytest tests
    - bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN
    - echo CODECOV_TOKEN
    - pytest --cov=./
    - echo "*****     Testing Sucessfull     *****"
    
after_success:
    - codecov -t CODECOV_TOKEN