language: python

python:
    - "3.7"

before_install:
    - sudo apt-get install python3-tk

script:
    - echo "starting script"
    - pip install -e .
    - pip install -r requirements.txt
    - echo "installed dependencies"
    - python src.
    - echo "starting script"