sudo: false

language: python

python:
    - "3.7"

before_install:
    - sudo apt-get install python3-tk

install:
    - pip install -r requirements.txt
    - pip install -e .

script:
    - pytest tests
    - pytest --cov=./src
    - bash <(curl -s https://codecov.io/bash)
    - flake8 cmdbox
    
after_success:
    - codecov -t CODECOV_TOKEN