version: '3.3'
services:
    mongo:
        image: mongo
        container_name: mazer-mongo
        hostname: mazer-mongo
        restart: unless-stopped
        command: mongod --auth
        environment:
            - MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD
        ports:
            - 27017:27017
        volumes:
            - mongodbdata:/data/db
        networks:
            backend:
                ipv4_address: 10.10.0.10

    mazer:
        image: mazer
        restart: always
        container_name: mazer-app
        build:
            context: .
            dockerfile: Dockerfile
        depends_on: 
            - mongo
        networks: 
            - backend
        ports: 
            - 80:80
        environment:
            - DEBUG
            - SECRET_KEY
            - MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD
            - MONGO_IP=10.10.0.10

networks:
    backend:
        driver: bridge
        ipam:
            config:
                - subnet: 10.10.0.0/21

volumes:
  mongodbdata:
    driver: local