version: '3.3'
services:
    mazer:
        image: mazer
        restart: always
        build:
            context: .
        ports:
            - 8001:8001
    mongodb:
    image: mongo:4.0.13
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
